# Generated by Django 3.2.6 on 2021-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('std_id', models.CharField(max_length=25)),
                ('national_id', models.CharField(max_length=25)),
                ('phone_num', models.CharField(max_length=25)),
            ],
        ),
    ]
