# Generated by Django 3.2.6 on 2021-09-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
