# Generated by Django 3.2.6 on 2021-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_Inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('std_id', models.CharField(max_length=25)),
                ('national_id', models.CharField(max_length=25)),
                ('phone_num', models.CharField(max_length=25)),
                ('upload', models.FileField(upload_to='files')),
            ],
        ),
        migrations.DeleteModel(
            name='student_info',
        ),
    ]
