# Generated by Django 3.2.6 on 2021-09-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20210903_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frequency',
        ),
    ]
