# Generated by Django 3.2.6 on 2021-09-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_delete_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='student_inf',
            name='time_choice',
            field=models.ManyToManyField(to='medical.time'),
        ),
    ]
