# Generated by Django 3.2.6 on 2021-09-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20210903_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='timer',
            field=models.DateTimeField(),
        ),
    ]
